### ISSUE TITLE
SDK Version is causing our mobile app to crash in Production

### ISSUE THREAD

**Issue by daricDava** [forcedotcom/ServiceSDK-iOS#58] opened 2018-12-19 07:44 UTC
Two days ago we filed an issue:
[https://github.com/forcedotcom/ServiceSDK-iOS/issues/56](url)

We were pointed to SalesforceMobileSDK-iOS. So we filed it in their page:
[https://github.com/forcedotcom/SalesforceMobileSDK-iOS/issues/2733](url)

Now after their investigation, they referred us back to Service SDK team. For continuity sake, kindly refer to these link we provided. May we have an update regarding resolution of our problem. Thank you.

**Comment by daricDava** [comment] 2018-12-21 02:14
HI @ashand-sf 

Kindly refer to these cases raised by our team for the context:
[https://github.com/forcedotcom/ServiceSDK-iOS/issues/56]()
[https://github.com/forcedotcom/SalesforceMobileSDK-iOS/issues/2733]()

Please also reopen issue #56

**Comment by MikeNachbaur** [comment] 2019-01-07 18:03
Since issue #56 has been reopened, and this is a duplicate of that one, I'll close this if you don't mind so we don't have any confusion.

**Closed by MikeNachbaur** 2019-01-07 18:03 UTC
