### ISSUE TITLE
216.0.1 Live Agent logger crashes in [sendJSON:withCompletion:]

### ISSUE THREAD

**Issue by chrisperkins** [forcedotcom/ServiceSDK-iOS#71] opened 2019-02-22 19:59 UTC
### Issue description
ServiceCore intermittently crashes on a background thread when attempting to log data. This app is a predominantly Swift project.

### Reproduction steps
Unable to reproduce as no pattern has emerged.

### Version of SDK components being used
216.0.1

### Device(s) and version(s) of iOS being used
iPhone 7, iOS 12.1.4
iPhone 7 Plus, iOS 12.1.2

### Screenshots / Videos
N/A

[SFCNetworkInstanceKey crash 1.txt](https://github.com/forcedotcom/ServiceSDK-iOS/files/2895584/SFCNetworkInstanceKey.crash.1.txt)
[SFCNetworkInstanceKey crash 2.txt](https://github.com/forcedotcom/ServiceSDK-iOS/files/2895585/SFCNetworkInstanceKey.crash.2.txt)

**Comment by aeisses** [comment] 2019-02-22 20:18
Hey Chris,

Thanks for sending this to up, we will look into it.

Aaron

**Comment by aeisses** [comment] 2019-03-28 18:14
Hey Chris,

We will have a fix for this issue in our next release. We were unable to reproduce it, so if you see it in the 220 release please let us know.

Thanks,
Aaron

**Closed by aeisses** 2019-03-28 18:14 UTC
