### ISSUE TITLE
'SCS_API_DEPRECATED_WITH_REPLACEMENT' macro redefined

### ISSUE THREAD

**Issue by Mourad-Aly** [forcedotcom/ServiceSDK-iOS#51] opened 2018-11-14 09:44 UTC
Hi,
I've tried the latest release https://github.com/forcedotcom/ServiceSDK-iOS/releases/tag/216.0.0, and I'm experiencing the following build error
```
#import "SCSChatUIDefines.h"
            ^
Pods/ServiceSDK/Frameworks/ServiceChat.framework/Frameworks/ChatUI.framework/Headers/SCSChatUIDefines.h:40:9: error: 'SCS_API_DEPRECATED_WITH_REPLACEMENT' macro redefined
    #define SCS_API_DEPRECATED_WITH_REPLACEMENT(__name) __API_DEPRECATED_WITH_REPLACEMENT(__name, ios(1.0,1.0))
            ^
Pods/ServiceSDK/Frameworks/ServiceCore.framework/Frameworks/ServiceCommon.framework/Headers/SCCDefines.h:213:9: note: previous definition is here
    #define SCS_API_DEPRECATED_WITH_REPLACEMENT(__name) __API_DEPRECATED_WITH_REPLACEMENT(__name, ios(1.0,100.0))
```
But it happens only when I run a build from fastlane, so it might be related to my setup and not `ServiceSDK-iOS` itself.
However, since it comes from `ServiceSDK-iOS` code, and it looks like the macro is defined in both `ServiceChat.framework` and `ServiceCore.framework`, I'd like to know if you know whether I miss-use the SDK somehow, or you think it's a known issue from `ServiceSDK-iOS` side, and if there is a fix for it.
Thanks!

**Comment by MikeNachbaur** [comment] 2019-01-07 18:02
This should be fixed in our upcoming release.  I'll close this since the work should be available when our next release is published.

**Closed by MikeNachbaur** 2019-01-07 18:02 UTC

**Comment by kravuri1987** [comment] 2019-01-24 00:06
Hi Mike,
We are experiencing the same issue . When will this fix be released be available?Is there any work around ? Appreciate your help.

**Comment by MikeNachbaur** [comment] 2019-01-24 18:36
@kravuri1987 You might be able to work around it in the short-term by importing the ServiceChat framework before ServiceCore.

**Comment by kiafire** [comment] 2019-01-24 20:16
@MikeNachbaur  I tried it and it didn't work out, can you provide any other pointers ? Is there be a GCC Macro that suppresses this ?

**Comment by MikeNachbaur** [comment] 2019-01-25 04:02
@kiafire  The root of the problem is a missing check for `#ifndef` around the definition for the macro, since the same macro is used in the other SDK frameworks.  All the other SDKs include that check, but it was missed in the Chat framework.  If you're able to, you can add a that check to the appropriate header in the ServiceChat.framework headers, until our upcoming release.

**Comment by kravuri1987** [comment] 2019-01-28 22:33
We are planning to release the sdk in the next 15 days.Can you please provide us a tentative dates for this fix.Lot of marketing and training materials are scheduled for this feature.It will be big help if you can support it.

**Comment by kravuri1987** [comment] 2019-01-28 22:44
@MikeNachbaur 
Can you please suggest a older version with zero issues so we go ahead with our release.

**Comment by MikeNachbaur** [comment] 2019-01-28 22:51
The 218 release is scheduled for February 12th. @kravuri1987 if you're able to change the headers of the ServiceChat.framework contents locally (either through changing the file locally, or using a build script to alter/replace the file before compile time), you can add the `#ifndef` / `#endif` wrapper around the macro definition to resolve this problem.

As far as a previous version, I believe that definition has been in there for a while.  The issue might be with recent versions of the Xcode compiler.  I wouldn't know for sure without researching it further.
