### ISSUE TITLE
App Crashes - Unable to reply to a case after opening in ServiceSDK v214.0.2 with MobileSDK v6.2.0

### ISSUE THREAD

**Issue by SanjeevGopalan** [forcedotcom/ServiceSDK-iOS#36] opened 2018-08-15 02:56 UTC
The SnapInSDK versions v214.0.x is unable to get token from MobileSDK v6.2.0. Even after we get the right token from the MobileSDK v5.3.1, the chat feature in SnapInSDK v214.0.x is not working, users cannot send message back to the backend. Any fixes to use Mobile SDK v6.2 with SnapIn SDK v214.0.x?

**Comment by SanjeevGopalan** [comment] 2018-08-16 12:48
Anyone who can help with this?

**Comment by ashand-sf** [comment] 2018-08-16 14:41
Can you please share a snippet of code that is not working? Thank you.

**Comment by MikeNachbaur** [comment] 2018-08-16 17:02
The Chat component of Snap-ins does not use authentication tokens to communicate, so utilizing the MobileSDK for Chat is unnecessary.  Please refer to our [Chat Quick Setup documentation](https://developer.salesforce.com/docs/atlas.en-us.noversion.service_sdk_ios.meta/service_sdk_ios/live_agent_basic_setup.htm) to verify that your Live Agent Chat settings are configured correctly.

**Comment by ngoccuong291** [comment] 2018-08-17 00:03
Sanjeev and I are working together, we're not using the LiveChat feature, we're using the CaseManagement.
After getting the `SFUserAccount` from the `SalesforceSDKCore 6.2.0` we create `SCSAuthenticationSettings`
`let authenticationSettings = SCSAuthenticationSettings(mobileSDK: account)`
`ServiceCloud.shared().setAuthenticationSettings(authenticationSettings, forServiceType: serviceType, completion: { (success, error) in`
But the `completion` block never got called back, we setup proxy to monitor the traffic between the phone and the backend and discover that the token created by the `SalesforceSDKCore` cannot be consumed by the `ServiceSDK 214.0.2`, downgrading to `SalesforceSDKCore 5.3.1` resolved the issue. The token created by `SalesforceSDKCore 5.3.1` got consumed easily by the `ServiceSDK 214.0.2`. However, even with this right token, after creating a case, getting into that case and try to reply back, the reply message never got sent back to the backend

**Comment by SanjeevGopalan** [comment] 2018-08-20 00:52
@ashand-sf - Were you able to check based on @ngoccuong291 's comments above? Thanks.

**Comment by MikeNachbaur** [comment] 2018-08-20 18:59
Interesting @ngoccuong291, we'll definitely look into the MobileSDK 6.2 compatibility shortly.  If you wish to continue using 6.2, you can fall back to using the SCSAuthenticationSettings [constructor that accepts the dictionary of OAuth values](http://forcedotcom.github.io/ServiceSDK-iOS/releases/api/214.0/Classes/SCSAuthenticationSettings.html#/c:objc(cs)SCSAuthenticationSettings(im)initWithOAuth2Dictionary:clientId:), and can pass them in separately.  In that way you can extract the appropriate values from the SFUserAccount object on-demand.

**Comment by ngoccuong291** [comment] 2018-08-21 04:05
update: `SalesforceSDKCore 6.2.0` start giving the right token to `ServiceSDK 214.0.2` but the users still can't reply back after opening a case

**Comment by amisha10** [comment] 2018-08-22 18:37
@ngoccuong291 : We were able to reproduce the issue with the user not able to reply on a case. It will be fixed in our next release in October.

**Comment by MikeNachbaur** [comment] 2018-09-13 00:40
@ngoccuong291 My apologies in the delay in my response.  We're aware of the problem, and we'll have a fix available in our next release (ETA October, though that is subject to change).

Thank you for your patience.

**Comment by ngoccuong291** [comment] 2018-09-14 05:09
@MikeNachbaur, @SanjeevGopalan told me that SalesForce iOS engineering team thought that the latest version of the ServiceSDK (214.0.3) should fix the issue so I tested, and I got a crash when I tried to reply to a case that I created before `Terminating app due to uncaught exception NSInvalidArgumentException', reason: '*** -getBuffer:length: only defined for abstract class.  Define -[SFCURLEncodedInputStream getBuffer:length:]!'`, so FYI the issue has not been fixed in the ServiceSDK 214.0.3

**Comment by MikeNachbaur** [comment] 2018-09-14 17:01
@ngoccuong291 Interesting error, do you have a full stack trace for that crash?

Also, what OS version and device are you on?

**Comment by MikeNachbaur** [comment] 2018-09-19 22:38
Thank you for all the great detail in this issue.  We have verified a fix and it should be generally available in our next release.

**Closed by MikeNachbaur** 2018-09-19 22:38 UTC
